### ISSUE TITLE
SRS Review: Improve Maintainability of the User Responsibilities Section

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#10]
The highlighted part about "requirement from SC" should be replaced with a link to the specific requirement (or assumption?) about input formatting.

![image](https://user-images.githubusercontent.com/11723492/66652176-0a195480-ec03-11e9-971f-8dc4f9af1d9e.png)

**Comment by sorainsm** [comment]
Alternatively, you could list this date formatting requirement as an input constraint and put it in Table 2.

I would think the physical constraints would be that the individual values fall in certain ranges (e.g. 01 <= month <= 12). 

@smiths do you think this would be an appropriate way to capture this formatting requirement? 

![image](https://user-images.githubusercontent.com/11723492/66652507-e1de2580-ec03-11e9-8be6-6921c3b1b02d.png)

**Comment by smiths** [comment]
@sorainsm, generally we would not include the input format as a user responsibility.  The software should check that the format is correct, and let the user know when it is incorrect.  There should definitely be a table for constraints on the input.  The table shown looks good, although the notation 90degreesN/S is ambiguous.  If the phi value is an angle and a compass direction, then it could be represented by a tuple.  I've added a type section to the template while discussing the SRS for @deemaalomair1 .  If a new type is needed for this SRS, a data type section would be helpful to make the SRS unambiguous.

Format and data constraints are different.  The format is the structure of the data.  For instance, the different parts of the input could be separated by spaces, or commas, or new lines.  Those would all be different input formats.  We don't normally specify the input format in the SRS.  We leave that to the design.  (Most projects will have an input format hiding module that will encapsulate the format secret.)

**Comment by sharyuwu** [comment]
@sorainsm Thank you for pointing this out.
Yes, it looks abstract to say "the requirement from SC", but based on what doctor smith said, I will still keep this line as it is.
@smiths  I have changed the notation of phi value to a tuple,(90^\circ,  N or S), and defined degree as a degree and N or S as a direction in the section of "table of units".
