### ISSUE TITLE
SRS Review: Internal Document Links Not Working

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#11]
Some of the references in the document aren't being called correctly in the LaTeX file, which causes them to show up as ?? in the pdf.

![image](https://user-images.githubusercontent.com/11723492/66652310-72683600-ec03-11e9-9711-9352e559a82f.png)

**Comment by sharyuwu** [comment]
@sorainsm  Thank you for pointing this out.
This issue has been fixed.
See https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL1081-L1082
