### ISSUE TITLE
SRS Review: Itemized List Bleeds Into Margin

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#12]
The itemized list for 5.1 Functional Requirements is bleeding into the margin and covers the page number. 

I think the issue may be resolved by recompiling the LaTeX.

![image](https://user-images.githubusercontent.com/11723492/66653258-96c51200-ec05-11e9-8d69-3615aa0fbfde.png)

_EDIT: I originally thought this was being captured as a table, and the issue might have been needing to use longtable instead. When I checked the LaTeX and saw it was an itemized list I think now it's just a compilation issue._

**Comment by sharyuwu** [comment]
@sorainsm Yes, I did try to fix this issue, but it seems like a compilation issue from Latex itself.
It might work if I change it from an itemized list to a table, which means I will have to change the template of this SRS.
@smiths if we could get your opinion on this, I'd appreciate it!

**Comment by sharyuwu** [comment]
@sorainsm Thanks again for pointing out this issue.
It was fixed by putting // at the end of every item.
See the changed line:
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/36b7501d5fc7515b07afd9b879c080ef6b313af7#diff-8111704a3cf481beeb1db94762a8804dL1170-R1171
