### ISSUE TITLE
SRS Review: Dr. Smith's Comments Still in PDF

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#14]
There were a few of Dr. Smith's comments that should be removed from the document.

![image](https://user-images.githubusercontent.com/11723492/66654030-4f3f8580-ec07-11e9-9712-68306e0fb6ac.png)

**Comment by sharyuwu** [comment]
@sorainsm Yes, I did try to put this comments in % or /iffalse..../fi but then I got a compiler error :(
so I will just have to leave them there for a while.
They will be fixed when I found out where the compiler error really came from!!

**Comment by sharyuwu** [comment]
I will keep this issue open to remind me this has to be fixed.

**Comment by sharyuwu** [comment]
@sorainsm  Thanks again for pointing out this issue.
I have found my missing command and go ride off this issue!
See https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL1199-R1260
