### ISSUE TITLE
SRS Review: Traceability Matrix Is Missing Entries

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#15]
The traceability matrix seems to be missing some of the connections.
For example: I see that R4 is connected to IM1 when I read the R4 row, but I don't see that IM1 is connected to R4 when I read across the IM1 row. I've highlighted the picture below to show the issue.

![image](https://user-images.githubusercontent.com/11723492/66654305-f0c6d700-ec07-11e9-8328-4b2e53169f3e.png)

There are quite a few connections like this missing but I have not listed all of them in the picture.

**Comment by sharyuwu** [comment]
@sorainsm  Thank you for pointing this out.
Indeed, there was some uncertainty when I build this table.
Combining the other posted issue https://github.com/sharyuwu/optimum-tilt-of-solar-panels/issues/8, my new document has removed the original IM1. Therefore, I changed the content of this table.
See the changing in Link:  https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL1238-L1244 
Please let me know your opinion about the new table content!
