### ISSUE TITLE
Revision History is not modified(#1)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [sharyuwu/optimum-tilt-of-solar-panels#16]
Hi Sharon,

Your revision history table is not modified yet, it's the one Dr.Smith gave in the example file.

**Comment by sharyuwu** [comment]
@best-zhang-zhi  can you please that a screenshot of that table you mentioned? Cause every table in the report has been modified. Or please pull the latest version and check if the issue still exists.
Thanks.

**Comment by smiths** [comment]
@sharyuwu, the revision history table is on page ii of your document.  The heading of the table is Revision History.  The dates, version numbers and notes are the same placeholders that are in the template.  You should replace these with actual dates of major revisions.

**Comment by sharyuwu** [comment]
It has been updated so I will close this issue.
See the changed line https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/62cfa1330c9174c049bb028429a1a4ff2ca92413#diff-8111704a3cf481beeb1db94762a8804dL102-R101
