### ISSUE TITLE
Spelling mistake(#2)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [sharyuwu/optimum-tilt-of-solar-panels#17]
Hi Sharon, 

In the first sentence in System Context section, you I think it's "users to the system then the output" but not "than the output".

**Comment by sharyuwu** [comment]
@best-zhang-zhi  Thank you for pointing this out. Yes, you are right it should be then instead of than.
See https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL432
