### ISSUE TITLE
Difficult to understand (#3)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [sharyuwu/optimum-tilt-of-solar-panels#18]
Hi Sharon, 

In SC Responsibilities, you wrote 
<img width="533" alt="Screen Shot 2019-10-12 at 5 30 12 PM" src="https://user-images.githubusercontent.com/55267358/66707885-f579b100-ed15-11e9-8b5a-235ce1e01c7e.png">
Did you mean "and to generate a report"?

**Comment by sharyuwu** [comment]
@best-zhang-zhi  Yes, you are right. It means to generate the output as a report format.
I have changed the way to express this idea.
See https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL432
