### ISSUE TITLE
Duplicated "RefBy" (#4)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [sharyuwu/optimum-tilt-of-solar-panels#19]
Hi Sharon, 
in the first Theoretical Models, 
<img width="259" alt="Screen Shot 2019-10-12 at 5 38 37 PM" src="https://user-images.githubusercontent.com/55267358/66707961-23abc080-ed17-11e9-82e0-d127f08f06e2.png">
There's duplicated "RefBy"

**Comment by sharyuwu** [comment]
@best-zhang-zhi  Thanks to pointing this out.
It has been correct.
see https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL718

**Comment by smiths** [comment]
@sharyuwu, thank you for including the information necessary for someone to determine if they agree with closing the issue.  It is also nice to see you closing the issues quickly.  😄
