### ISSUE TITLE
list of functional & non-functional requirements 

### ISSUE THREAD

**Issue by deemaalomair1** [sharyuwu/optimum-tilt-of-solar-panels#24]
Hello ,
 In the document you referenced SRS document for related information .. so i think it's not important to list all functional and non-functional requirements in V&V. It is kind of repeating.

![Screen Shot 2019-11-07 at 11 22 22 AM](https://user-images.githubusercontent.com/45468077/68408165-dd4d5400-0152-11ea-8fb1-196a7395e835.png)

**Comment by sharyuwu** [comment]
@deemaalomair1  I feel it is necessary to put this information in my document. Although you are right, it is a piece of repeat information from my SRS. 
I feel having it listed out can enhance the traceability and the clarity of my document. 
So I will close this issue.
