### ISSUE TITLE
How test will be performed

### ISSUE THREAD

**Issue by deemaalomair1** [sharyuwu/optimum-tilt-of-solar-panels#26]
in more than one place you wrote 
How test will be performed:
 1. Input the value from the keyboard following the instruction of the software interface.
 2. verified the output showing on the screen by the test case derivation instruction.
i think you need to identify if it is parallel or coverage or unit in this part ..

**Comment by sharyuwu** [comment]
Change the description.
Please review the new document for the improvement.

https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/VnVPlan/SystVnVPlan/SystVnVPlan.pdf
