### ISSUE TITLE
VnV Review: Typo in Section 2, and 5

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#29]
Hi Sharon, there's a typo in section 2 (highlighted below).
Should be "latitude", seems like an "a" accidentally slipped in 😄 
![image](https://user-images.githubusercontent.com/11723492/68717073-c99b5680-0573-11ea-9414-bb411bc25672.png)

**Comment by sorainsm** [comment]
Same issue is Section 5.1.1
Should be "Identify"
![image](https://user-images.githubusercontent.com/11723492/68718644-d3bf5400-0577-11ea-9427-47b78fa8da89.png)

**Comment by sharyuwu** [comment]
Corrested
