### ISSUE TITLE
Remove unnecessary material from your repo

### ISSUE THREAD

**Issue by smiths** [sharyuwu/optimum-tilt-of-solar-panels#3]
@sharyuwu,  your repo is huge!  You should just have the project content in your repo, not the course content.  Please remove the course content.  You have reference material (pdfs of papers) that are not publicly available; they should not be on a public site.

All you want in your repo is the folder structure represented at:

https://gitlab.cas.mcmaster.ca/smiths/cas741/tree/master/BlankProjectTemplate

**Comment by sharyuwu** [comment]
@smiths Thank you for sending me this issue.
I have deleted all the personal and unnecessary files.

In the original SRS blank template, the graphic "RelationsBetweenTM_GD_IM_DD_A.pdf" was linked to the file /Lecture/Figures/. To solve this issue, I changed the address of the graphic copying it individually to the file /docs/SRS.

To see the changed line 

https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/d5ada1c10873b6ad3f658355efb13df6407c8a6d#diff-b394d3af432a50640241fac6fce3ef25

**Comment by smiths** [comment]
Yes, @sharyuwu the new repo organization is much better.  However, you still have a bit to do.  Some of the contents of your Doc folder are not documents.  For instance, you also have the src folder inside the Doc folder.  This is what you want at the top level of your folder structure:

https://github.com/sharyuwu/optimum-tilt-of-solar-panels/tree/master/Doc

That is, the Doc folder should be removed and everything below it promoted up one level.

Thank you for pointing out the issue with the original SRS.  I have changed the blank template to match your changes.  (Done in https://gitlab.cas.mcmaster.ca/smiths/cas741/commit/96ca2043b43ac7b8f7d44f5b5240abfaa763ecc9)

**Comment by sharyuwu** [comment]
Yes, @smiths the DOC file has removed, and the files inside the file were pushed to an upper layer.

**Comment by smiths** [comment]
Once you have resolved an issue, feel free to close it.  (You don't need me to close it.  I can reopen the issue if I have something further to add.)
