### ISSUE TITLE
VnV Suggestion: Change symbol "date" to something that indicates duration

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#30]
Hi Sharon,
Just a suggestion, the use of _date_ as a symbol representing a period of time is a little confusing when reading through the document.
While it's clear what you're using it for, people may come back to this document and not read it from top to bottom, and so I think changing _date_ to either _period_ or _days_ would imply that it's a duration rather than just a singular date.

![image](https://user-images.githubusercontent.com/11723492/68717283-5e05b900-0574-11ea-88dd-b97351714b80.png)

**Comment by sharyuwu** [comment]
@sorainsm Thank sora:) This is great advice. I have been struggled a lot with how to make this variable more explicit. I will think about the name you offered.
I will leave the issue open to think about it.

**Comment by smiths** [comment]
@sharyuwu, I think the concept of date and time will become more clear to you when you complete your MIS.  I'm fairly sure you will be introducing an ADT for date.  Your choice of interface to this ADT will show you what date related calculations you  need.  To clarify your SRS and VnV plan, you might want to go back and add a date type to these documents.

**Comment by sharyuwu** [comment]
@smiths  Yes, I have followed your advice on adding a data type in my SRS but haven't updated it. I will at a link to this issue after updating my document.

**Comment by sharyuwu** [comment]
I have added an additional explanation to this confusion.
Hope it help!!
![image](https://user-images.githubusercontent.com/55363335/71295639-d9644280-234a-11ea-95cd-81dddd04d122.png)

https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/SRS/SRS.tex#L854
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/VnVPlan/SystVnVPlan/SystVnVPlan.tex#L75
