### ISSUE TITLE
VnV Review: Typo (missing spaces) in Section 3, and 5

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#31]
Hi Sharon,
Another easy fix typo - there are spaces missing between some words just before Section 3's title.
![image](https://user-images.githubusercontent.com/11723492/68717398-b3da6100-0574-11ea-9943-c9fa836b4676.png)

**Comment by sorainsm** [comment]
Same issue in Section 3.1
![image](https://user-images.githubusercontent.com/11723492/68717462-d8ced400-0574-11ea-9cd8-2efb420dc969.png)

**Comment by sorainsm** [comment]
Same issue in Section 5.1.1.
![image](https://user-images.githubusercontent.com/11723492/68718538-8cd15e80-0577-11ea-946d-363c74c7168f.png)

**Comment by sharyuwu** [comment]
Thank you for pointing this out.
And sorry for the hard reading.
I was trying to wrap every line to 80 columns, and after I did it everything mass up....
I hope that I have fixed them all
