### ISSUE TITLE
VnV Review: Requirement 7 is too generic

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#32]
Hi Sharon,
I think that R7 (see figure below) should be stated in terms of the system's actions, like the other requirements are, and potentially be more specific. I think this is possible since you have that big data set that you will be pulling information from.

e.g. R7: The system should verify the output against the data from (...)

![image](https://user-images.githubusercontent.com/11723492/68717709-788c6200-0575-11ea-8e30-2c6c707a0374.png)

**Comment by sharyuwu** [comment]
I was meant to say the software should able to verify the output by using the table of outputs constraint.
The statement only remains in my SRS now, it was deleted from my SystemVnVPlan.
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/SRS/SRS.tex#L1485
