### ISSUE TITLE
VnV Question: R8 is unclear, please explain what the rationale was behind it.

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#33]
Hi Sharon,
I'm unclear what you're trying to say with R8 (see below).
The part that confuses me is the "in a manner consistent with decision making" - do you mean the decisions you've made in the system design, or decision making for the user (i.e. to make it easy for them to make decisions based on this information)?

Is this trying to say that the output will be in a specific format (like with R2)?

![image](https://user-images.githubusercontent.com/11723492/68717974-0cf6c480-0576-11ea-819b-5e7391297b65.png)

**Comment by sharyuwu** [comment]
I meant to say that the system output should remain consistent with the corresponding of the input values.
In other words, if input the same values the software should output the same result.
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/SRS/SRS.tex#L1492
