### ISSUE TITLE
VnV Suggestion: Listing Verification and Validation Team Members

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#34]
Hi Sharon,
You specifically list myself and Zhi as reviewers for the SRS; I think that it is worthwhile to list the other class members as part of the verification and validation team as well, and move this information up to Section 4.1

![image](https://user-images.githubusercontent.com/11723492/68718211-95756500-0576-11ea-9091-b88de739a667.png)

**Comment by sharyuwu** [comment]
@sorainsm  Yes, your right.
I once though the member of the "Verification and Validation team" is only for the people who will review my VnV Plan. It should be the members who will help me verify the whole project.

**Comment by smiths** [comment]
Yes, I agree.

**Comment by sharyuwu** [comment]
Listed
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/VnVPlan/SystVnVPlan/SystVnVPlan.tex#L157
