### ISSUE TITLE
VnV Suggestion: Author Name Consistency

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#35]
Hi Sharon,
I think it would be a good idea to keep your name consistent.
Somebody jumping past the title page straight to Section 4 might be confused.
Personally I like how it is on the title page _Sharon (Yi-Shiuan) Wu_ as it makes it clear who you are 😄 

![image](https://user-images.githubusercontent.com/11723492/68718308-d53c4c80-0576-11ea-8883-3e0b6037888f.png)

**Comment by sharyuwu** [comment]
Yes, I will make them consistent!
Thank you for pointing this issue put.
It is so easy to mass them up when I am using two names at the same time:(
