### ISSUE TITLE
VnV Suggestion: Change Input Tests from Manual to Automatic Tests

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#36]
For all the input tests (InputReading-id1, InputBounds-id2, etc) it's stated that it's a manual test - I assume this is because the input is from the keyboard.

I think it is possible for you to run an automatic test with this, where you can set up what the system behaviour ought to be and then run those tests.

From Googling around I found HSpec (http://hspec.github.io/). It is supposed to be compatible with QuickCheck (which you say you're using) and HUnit (which is likely something you'll use for your unit tests). So I think it's worthwhile looking into.

**Comment by smiths** [comment]
Yes, @sorainsm is correct.  @sharyuwu, you really should be targeting automatic tests.

**Comment by sharyuwu** [comment]
@smiths  Yes:) I also agree with @sorainsm, and I definitely will look into it.

**Comment by sharyuwu** [comment]
Corrected
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/VnVPlan/SystVnVPlan/SystVnVPlan.pdf
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/VnVPlan/UnitVnVPlan/UnitVnVPlan.pdf
The testing framework is likely to be changed. I put using the framework, Tasty, in my document.
But it might change if I later find out HSpec or other frameworks work better.
