### ISSUE TITLE
VnV Review: Format of InputBounds-id2

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#37]
Hi Sharon,
The format of InputBounds-id2 should end lines where I drew the red lines below.
This will keep it consistent with the formatting from the template, and make it easier to read.

![image](https://user-images.githubusercontent.com/11723492/68719411-ee92c800-0579-11ea-80b0-de129353aee4.png)

**Comment by sharyuwu** [comment]
Corrected
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/VnVPlan/UnitVnVPlan/UnitVnVPlan.tex#L157
