### ISSUE TITLE
VnV Review: InputBounds-id2 - input(2) and output (2) should be -90

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#38]
Hi Sharon,

There seems to be a typo with input (2), as it reads 90 but should be -90.
The same applies to output (2) - both highlighted below.

![image](https://user-images.githubusercontent.com/11723492/68719521-492c2400-057a-11ea-9fb8-111d5b2a92e5.png)

**Comment by sharyuwu** [comment]
Corrected
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/VnVPlan/UnitVnVPlan/UnitVnVPlan.tex#L157
