### ISSUE TITLE
VnV Question: Separating Inputs for Test Cases

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#39]
Hi @smiths can you clarify for me how the test cases should be split up?
I was under the impression that we should have separate test cases with individual specific input, but is it possible to have it as Sharon has it (one broad test category with the different test inputs and outputs listed?) 

Her method seems more efficient in capturing how the tests relate to each other. Is this a case where it's up to the author of the document which they think makes the system more understandable?

![image](https://user-images.githubusercontent.com/11723492/68719680-c192e500-057a-11ea-877f-1d5184fe94b9.png)

**Comment by smiths** [comment]
@sorainsm, it should be possible to easily identify the individual tests from the document, but that does not mean that each needs its own separate test description.  In many cases test cases will be identical, except for changing one input (or one state).  It would be very repetitive to write them all out in full.  It is completely acceptable to use a table, or other device, to summarize multiple tests together.
