### ISSUE TITLE
Discussing about the extra function of my project 

### ISSUE THREAD

**Issue by sharyuwu** [sharyuwu/optimum-tilt-of-solar-panels#41]
@smiths 
Hi Doctor Smith,

About adding the function that can allow users to evaluate the results from different input(different date duration), I have been thinking this for a while. Then I thought I could either draw the result out with an x-axis,  y-axis graphic or compare the average solar energy absorption then present the result by a table. By doing so, I might be able to give a clear image of the result of the calculation.
Do you think this plan is suitable?

And about the feedback from my VnVplan, by assessing usability you mentioned, is it means that testing the end-user experience?

**Comment by smiths** [comment]
@sharyuwu I think the comparison between different date durations best lends itself to a table.  I'm not sure what you would draw graphically.  You could do a histogram, but I think the table approach will be easier for you.

Yes, usability is related to the end-user experience.  Ao and @sorainsm have details in their VnV plans on assessing usability.
