### ISSUE TITLE
Output Parameters Module: Unclear meaning

### ISSUE THREAD

**Issue by caobo1994** [sharyuwu/optimum-tilt-of-solar-panels#45]
> Secrets: The parameters of outputs.
> Service: Assigns the calculated results to output parameters.
My understanding of this sentence is that after this operation, the output parameters will exactly be the calculated results, but they are still in the realm of this software, unknown to the outside world. Where is the step that interacts with the environment variables?

**Comment by smiths** [comment]
I agree with @caobo1994.

**Comment by sharyuwu** [comment]
My original design is to let the output parameter collect the data and then send the data to the table-layout to display on the screen.
But it does not really make sense as you said, the output parameters will exactly be the calculated results, but they are still in the realm of this software.
So then I combine the output parameter module and table-layout module. In other words, the table-layout module has the secret of collecting the data and output them with the correct format.
