### ISSUE TITLE
Need help! Is it understandable?

### ISSUE THREAD

**Issue by sharyuwu** [sharyuwu/optimum-tilt-of-solar-panels#46]
Hi reviewers @smiths  @sorainsm  @caobo1994 ,
I rewrote one of my local function as following. It still a long-expression. Please give me some feedback on the understandability of this expression. I will use natural language to explain what does this function means.

![image](https://user-images.githubusercontent.com/55363335/70162498-bddf1380-168b-11ea-9aa3-4b9505915e68.png)
setdurlist is a local function that takes two DayT and returns a sequence of integers.

If staDay is smaller or equal than inpDay 
1) add an integer into the sequence daduraL
2) get the next day of staDay then run setdurlist again. 

Until staDay is greater than inpDay
1) Stop the recursion.

Here is the expression of compare function.
![image](https://user-images.githubusercontent.com/55363335/70161473-1c0af700-168a-11ea-8358-7da959aecd41.png)

Here is the expression of countdiff function.
![image](https://user-images.githubusercontent.com/55363335/70161534-32b14e00-168a-11ea-8fb1-d3b9a5a12bcc.png)
It is counting the days from input day1 to input day2.

Here is the expression of getnext.
![image](https://user-images.githubusercontent.com/55363335/70161736-93408b00-168a-11ea-9747-abee0b648d8a.png)
It is getting the next day of input d.

Here is the expression of perihelion.
![image](https://user-images.githubusercontent.com/55363335/70162218-4dd08d80-168b-11ea-9156-ab06b342c9c0.png)
It is getting a day based on input day.

**Comment by smiths** [comment]
@sharyuwu, your `compare` is much longer than it has to be.  The semantics can simply be:

`compare(d1, d2) := d1 <= d2`

As we discussed on another thread, you need to define `<=` for DayT, but once you have that, the above is all you need.

You also don't need in your `setdurlist` function to compare to `True` and `False`.  The values of the Boolean expressions will already be either `True` or `False`.  You are also using the wrong rightarrow notation in  your `setdurlist` function.  You want the arrow for a conditional rule.  I do not think you need recursion for your `setdurlist`.

I really think you are making this more complicated than it has to be.  I'm not convinced that you need lists (sequences) as outputs of your functions.

**Comment by sharyuwu** [comment]
@smiths 
If I defined the function of <, < =, then also define compare(d1, d2) := d1 <= d2.
Will the function compare(d1, d2) := d1 <= d2 seems redundant?

**Comment by sharyuwu** [comment]
Yes, I will reconsider the reason for having the function setlist.
Maybe I don't really need it.

**Comment by sharyuwu** [comment]
@smiths  I remove the function of setdurlist and expose some local function to Exported Access Programs. 
See the changed line in https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/48be4e50631134c57ea767521ed7946f14a10806#diff-b1bd046f21124a53c1bb4ef387323431L329-R333
I will close this issue because the change was made.
But help give me some comments about the change.
