### ISSUE TITLE
Semantics of setlist

### ISSUE THREAD

**Issue by caobo1994** [sharyuwu/optimum-tilt-of-solar-panels#48]
I see you use concatenation twice in this function. One is the beginning, and the other one is [day, ...]. I think only one of them is needed, and I suggest that you remove the first one.

**Comment by sharyuwu** [comment]
Yes,
I am working on this module now and this setlist has changed.

https://github.com/sharyuwu/optimum-tilt-of-solar-panels/issues/46
This is what it looks like right now. 

![image](https://user-images.githubusercontent.com/55363335/70183859-994b6180-16b4-11ea-8c35-945754fedadf.png)

And the new local function will be called by getdurlist.
Please give me feedback on the new local function!! Thank you

**Comment by caobo1994** [comment]
This new content is unavailable in your online git repo. Could you push it? Thanks!

**Comment by sharyuwu** [comment]
Sure:) but I am still continually changing it:)

**Comment by sharyuwu** [comment]
Yes I HAVE PUSH it.
But please notice that I am still working on the documents:)

**Comment by sharyuwu** [comment]
Extended discussion on https://github.com/sharyuwu/optimum-tilt-of-solar-panels/issues/51
