### ISSUE TITLE
Syntax of getnext

### ISSUE THREAD

**Issue by caobo1994** [sharyuwu/optimum-tilt-of-solar-panels#49]
What is the meaning of the second parameter of getnext? It seems that you only need to know the next day after d1.

**Comment by sharyuwu** [comment]
Yes, this function has also be changed!
This is what it looks like now.
![image](https://user-images.githubusercontent.com/55363335/70184070-124ab900-16b5-11ea-80aa-97b45af023c2.png)

The new version of MIS will be posted shortly:)
Please give me feedback on the new modified function.
