### ISSUE TITLE
SRS Review: Readability Improvements

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#5]
@sharyuwu I've highlighted some typos and drew a line through parts of sentences that could be removed for conciseness.

![image](https://user-images.githubusercontent.com/11723492/66616152-9db83a00-eb9d-11e9-8c3d-dea464dbadc6.png)

When removing that second sentence, put the abbreviation in brackets after the name. I.E. Sun Catcher (SC).

**Comment by sorainsm** [comment]
The following two instances should be "based".

![image](https://user-images.githubusercontent.com/11723492/66618374-e0324480-eba6-11e9-9826-447a0b3349e2.png)
![image](https://user-images.githubusercontent.com/11723492/66618389-ea544300-eba6-11e9-9191-0d33ef375d89.png)

**Comment by sharyuwu** [comment]
@sorainsm  Thank you for pointing out the spelling mistake.
And yes, I agree with you that removing those sentences you pointed out can make the content more concise.

**Comment by sharyuwu** [comment]
The changed line can be reviewed in the link https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/a38b9eca2d06a9d056008d8b41b89713e275ad02#diff-590bd3df8400453a6e28fafa3be135a5

**Comment by smiths** [comment]
Thank you for the comments @sorainsm.  Good job with quickly addressing the concerns @sharyuwu, and then including the hash of the commit that closes the issue.  The only thing you forgot to do was actually close the issue.  :smile:
