### ISSUE TITLE
display: show a table horizontally on screen

### ISSUE THREAD

**Issue by caobo1994** [sharyuwu/optimum-tilt-of-solar-panels#50]
Usually, when reading some long contents, people scroll up and down, not left and right. However, this table has infinite number of columns, but finite number of rows, so the table can be too long horizontally to be contained in one single screen. It is counter-intuitive for people to read. I suggest that you do a row<->column change, and show this table vertically.

**Comment by sharyuwu** [comment]
![image](https://user-images.githubusercontent.com/55363335/70184251-78cfd700-16b5-11ea-98a4-7206124a0283.png)
I believe this is the table you mentioned.
I am not expecting infinite output because the row of the table is depended on |resultL| AND |resultL| will depend on how many times users run this software.
However, I do decide to change the design of this table!
So I will leave this post open and close after the change.

**Comment by smiths** [comment]
@sharyuwu, if you are displaying a table to the screen, you want to add an environment variable to represent the screen.

I like the generality that you are aiming for, but your project will be simpler if you decide in advance what scenarios you want to run for the user.  They can give the start date and the end date and you can a priori decide some options to compare.  As I've mentioned before, having a sequence that stores all of the results is potentially confusing.  How does someone know the meaning of the ith index into resultL?  If you decide what scenarios you are going to run, you can have more meaningful variable names than indexing into a sequence.  This is highlighted by the fact that your table above does not have column headers.  I don't think you know what to call these columns, which means the user has to keep track of the meaning of each index?  I might be missing something, but I think you are still better off with a simpler design.

**Comment by sharyuwu** [comment]
@smiths @caobo1994 
The new design displays the table in a file.
And also I rearrange the design of the table.
Now I will produce two for the result.
1. Show the difference energy based on the number of the cut.
2. Show the angles for adjusting the solar panel based on the day.
![image](https://user-images.githubusercontent.com/55363335/71206826-8ec3c700-2273-11ea-925a-3064f404d8e7.png)
