### ISSUE TITLE
Discussion about rather should I merge the modules

### ISSUE THREAD

**Issue by sharyuwu** [sharyuwu/optimum-tilt-of-solar-panels#52]
Hi, reviewers @smiths  @sorainsm  @caobo1994 
Can you give me some advice on rather should I merge the modules?
![image](https://user-images.githubusercontent.com/55363335/70197524-2bb22c00-16da-11ea-82b4-28b3657fe468.png)
Here is my hierarchy graph.
I am thinking rather should I merge the Zenith Angle Module and Sun Intensity Module.
The modules for this program are all small. 
I guess because of the scope of my moduled, it is a reason to merge them.
But I think these two modules are doing different things so I don't want to merge them. Although it is true they are all calculating something.
But they are also calculating different things.

**Comment by caobo1994** [comment]
You cab try to merge read/input modules.

sharyuwu <notifications@github.com> 于 2019年12月4日周三 21:16写道：

**Comment by sharyuwu** [comment]
@caobo1994 Agree!
read/input modules will be merged in the next updated version

**Comment by sharyuwu** [comment]
Thank you all for the command.
In the end, I merger 
Input parameter module + read file module = Input/Read Parameter
Module
Sun Intensity module + Zenith angle module = Calculation Module
Output parameter module + table-layout module =  Table-layout 
Module

See the updated figure at
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/Design/MG/Fig_Hierarchy.jpg
