### ISSUE TITLE
Instructions for running your code

### ISSUE THREAD

**Issue by smiths** [sharyuwu/optimum-tilt-of-solar-panels#55]
@sharyuwu please add instructions for how to run your code.  I would like to test your program, but your folder structure and naming convention don't immediately suggest to me where I should put my efforts.  It will be much easier if you add a README file that explains the steps for running your program.  You should include the expected version of Haskell and any library dependencies.  I would also like the instructions for running your automated tests.

**Comment by sharyuwu** [comment]
I have instruction in the readme file under file, scr.

https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/src/README.md
Sorry that the test have to be done manually.
I will get rid of this issue as soon as possible.

**Comment by sharyuwu** [comment]
The automated test is still in progress.
Sorry for the inconvenience.

**Comment by sharyuwu** [comment]
The instruction is also in here too!
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/src/INSTALL.txt

**Comment by smiths** [comment]
@sharyuwu, I'm sorry but your instructions do not work.  Maybe you are missing some details?

**Comment by sharyuwu** [comment]
Let me try my instruction on other editor and see how its work.

**Comment by sharyuwu** [comment]
Yes, I did miss some detail.
The tool stack has to be install.
Here is the additional instruction: Install stack (1.2.0 or latter).

**Comment by smiths** [comment]
I successfully ran your code.

**Comment by sharyuwu** [comment]
Thank you for helping me tested out!
Automatic test cases and the expanded function are on its way!
It takes me some time to understand how to make user interactive automatically.

**Comment by smiths** [comment]
@sharyuwu, we are actually quite a ways past the deadline now.  The final report was due on the 18th.  I need to complete the grading.  I can give you until Dec 21, 11:59 pm to finish your testing.

**Comment by sharyuwu** [comment]
OK! Copy that
