### ISSUE TITLE
Suggestion: Replace Wikipedia Sources

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#7]
You should replace the Wikipedia references for your TMs and equations with textbook references to make it more credible.

![image](https://user-images.githubusercontent.com/11723492/66617839-c263e000-eba4-11e9-83af-d7b8bd01f470.png)

The linked wikipedia page has good references for this at the bottom:
![image](https://user-images.githubusercontent.com/11723492/66618065-c04e5100-eba5-11e9-8eec-3e997795129c.png)

**Comment by smiths** [comment]
I also agree with this advice.  Wikipedia is great for quickly learning, but it generally shouldn't be cited in scholarly work.

**Comment by sorainsm** [comment]
If you decide to change the references (and even when you're just citing other URLs) you should add them to the .bib file so they will show up in your references section.

![image](https://user-images.githubusercontent.com/11723492/66655038-641d1880-ec09-11e9-8a5c-b42fedee9205.png)

**Comment by sharyuwu** [comment]
@sorainsm Thank you for pointing this out.
More reliable sources have added and cited in this document.
See https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL715
