### ISSUE TITLE
Suggestion (SRS): General Definition Should be a Data Definition

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#8]
I think that your GDD should actually be a DD. It doesn't look like it's a refinement on the TM, just an equation used in solving the problem.

I've included images of both the TM and GDD side by side to show that there's no refinement from one to the other. @smiths if we could get your opinion on this, I'd appreciate it!

![image](https://user-images.githubusercontent.com/11723492/66618214-58e4d100-eba6-11e9-92e1-3157fee9faed.png)
![image](https://user-images.githubusercontent.com/11723492/66618182-38b51200-eba6-11e9-9a3a-1f0624eddbc2.png)

**Comment by smiths** [comment]
Yes, I agree with @sorainsm.  The GD appears to be a DD.  The clear hint is that writing it did not require a reference to a TM or other GD.  If it refined something,  you would have referred to it.

**Comment by sharyuwu** [comment]
@sorainsm Thank you for pointing this out.
It gives me a chance to think about the order of the method I used. I have changed the Calculate of the 
Zenith angle to Data Definition like you said it was not refining anything.

See the changed line in the link: https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dR762-R822

Moreover, I rearrange the Calculate of Sun intensity to General definition. I will post an issue about this change.  Please let me know your opinion!
