### ISSUE TITLE
SRS Review: Figure Missing Captions

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#9]
This figure is missing a caption.

![image](https://user-images.githubusercontent.com/11723492/66619081-94cd6580-eba9-11e9-9767-514bed598909.png)

**Comment by sharyuwu** [comment]
Thank you for pointing this out.
The label has been added.
See the changed line:
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/48942d44dc5485daa07e4f8586bc958605d1e8c1#diff-590bd3df8400453a6e28fafa3be135a5
